"""add bridge recent searches

The one per-user table in the bridge subsystem: which topics a student looked up
for a step, so a finished search has somewhere to land instead of vanishing when
its run leaves the queued/running state.

Pure addition — no existing table is touched and no data is backfilled. Searches
made before this migration are not recoverable: cache hits never wrote a row at
all, and while bridge_jobs holds the misses, replaying them would date every
entry to the original run and reorder lists by history rather than by what the
student actually looked at recently.

Revision ID: 3add04d1e97a
Revises: a3c9e51f7d24
Create Date: 2026-08-21 13:47:35.332580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3add04d1e97a'
down_revision: Union[str, Sequence[str], None] = 'a3c9e51f7d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_recent_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.String(length=50), nullable=False),
    sa.Column('topic_slug', sa.String(length=120), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model_id', 'topic_slug', name='uq_bridge_recent_user_model_topic')
    )
    op.create_index(op.f('ix_bridge_recent_searches_id'), 'bridge_recent_searches', ['id'], unique=False)
    op.create_index(op.f('ix_bridge_recent_searches_user_id'), 'bridge_recent_searches', ['user_id'], unique=False)
    op.create_index('ix_bridge_recent_user_model_time', 'bridge_recent_searches', ['user_id', 'model_id', 'searched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bridge_recent_user_model_time', table_name='bridge_recent_searches')
    op.drop_index(op.f('ix_bridge_recent_searches_user_id'), table_name='bridge_recent_searches')
    op.drop_index(op.f('ix_bridge_recent_searches_id'), table_name='bridge_recent_searches')
    op.drop_table('bridge_recent_searches')
    # ### end Alembic commands ###
