"""add read_only to exercises

Revision ID: 8853ed467afc
Revises: 3cd56dbaa6ed
Create Date: 2026-07-10 19:34:00.296295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8853ed467afc'
down_revision: Union[str, Sequence[str], None] = '3cd56dbaa6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default=false() so the NOT NULL add is safe even against a table
    # that already has rows (the model's default=False is Python-side only and
    # does nothing at the DB level for existing rows).
    op.add_column(
        'exercises',
        sa.Column('read_only', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'read_only')
    # ### end Alembic commands ###
