"""make starter_code and solution_code nullable

Revision ID: 9f441d9e1503
Revises: 8853ed467afc
Create Date: 2026-07-13 12:55:22.562415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f441d9e1503'
down_revision: Union[str, Sequence[str], None] = '8853ed467afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'starter_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_solutions', 'solution_code',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_solutions', 'solution_code',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('exercises', 'starter_code',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
